MugedaHelper={};function G(a){return document.getElementById(a)}function E(a,d,b){d||(d="load");b||(b=window);b.attachEvent?b.attachEvent("on"+d,a):b.addEventListener(d,a,false)}function json(a){try{return eval("("+a+")")}catch(d){return null}}function _AC(a){if(!a||typeof a=="string")return a;var d="",b;for(b in a)d+="&"+b+"="+encodeURIComponent(a[b]);d&&(d=d.substr(1));return d}
function ajax(a){var d=/POST/i.test(a.type),b=a.data||"",e=a.dataType,f=a.url||location.href,c=/\?/.test(f)?"&":"?",g=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP")||new ActiveXObject("Microsoft.XMLHTTP");g.onreadystatechange=function(b){if(g.readyState==4)g.status==200?(b=g.responseText,e=="json"&&(b=json(b)),(d=a.success)&&d(b)):a.error&&a.error(g.status,g)};if(typeof b=="object"){var k=[],h;for(h in b)k.push(encodeURIComponent(h)+"="+encodeURIComponent(b[h]));b=k.join("&")}g.open(d?
"POST":"GET",f+(d?"":(b?c:"")+b+(a.cache?"":(!b&&c=="?"?"?":"&")+(a.cache_ok?"":"_="+(new Date).getTime()))),a.async===false?false:true);d&&g.setRequestHeader("Content-Type","application/x-www--urlencoded");g.send(b);return g}
var ajaxHelper=function(a){a=a||{};a.method=a.method||"GET";a.type=(a.type||"text").toLowerCase();a.jsonp_callback=a.jsonp_callback||"callback";a.success=a.success||function(){};a.error=a.error||function(){};a.cache_ok=a.cache_ok||false;a.url=a.url||(a.error({status:-5,desc:"Empty url"}),"");a.cache_ok||(a.url+=a.url.indexOf("?")>-1?"&":"?",a.url+="_mats="+(new Date).getTime(),a.url+="&callback="+a.jsonp_callback);if(a.type=="jsonp"){var d=false;window[a.jsonp_callback]=function(b){d=true;a.success(b)};
var b=document.getElementsByTagName("head")[0],e=document.createElement("script");e.type="text/javascript";e.src=a.url;e.onload=function(){d||a.error({status:-3,desc:"jsonp not loaded correctly for the URL "+a.url})};e.onerror=function(){a.error({status:-2,desc:"Failed to load the url: "+a.url})};b.appendChild(e)}else{var f;window.XMLHttpRequest?f=new XMLHttpRequest:a.error({status:-3,desc:"Platform not supported"});f.onreadystatechange=function(){if(f.readyState==4)if(f.status==200){var b="ok";if(a.type==
"json")try{a.success(JSON.parse(f.responseText))}catch(d){b=d.toString(),a.error({status:-6,desc:"Error in parsing JSON ("+b+")"})}else a.type=="data"?a.success(f.response):a.type=="text"&&a.success(f.responseText)}else a.error({status:f.status,desc:"Error in fetching data (code "+f.status+")"})};if(a.type=="data")f.responseType="blob";f.open(a.method,a.url,true);f.send()}};
function isMobile(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?true:false}function fo(a){var d=0,b=0;do d+=a.offsetLeft||0,b+=a.offsetTop||0;while(a=a.offsetParent);return{x:d,y:b}}function fe(a){a=a||event;return{x:a.pageX||a.x,y:a.pageY||a.y}}
function fc(a){a&&a.stopPropagation?a.stopPropagation():event.cancelBubble=true}function getClass(a,d){for(var b=RegExp("(^|\\s*)"+a+"(\\s*|$)"),e=d?document.getElementsByTagName(d):document.getElementsByTagName("*")||document.all,f=[],c=0,g=e.length;c<g;c++)b.test(e[c].className)&&f.push(e[c]);return f}JSON.clone=function(a){return JSON.parse(JSON.stringify(a))};
function getElementOffset(a){for(var d=0,b=0;a&&a.tagName!="BODY";)d+=a.offsetTop,b+=a.offsetLeft,a=a.offsetParent;return{top:d,left:b}}var MugedaTools=window.MugedaTools=window.MugedaTools||{};
MugedaTools.message=function(){var a,d=[],b={},e=function(){var a=window.getComputedStyle(document.documentElement,""),a=(Array.prototype.slice.call(a).join("").match(/-(moz|webkit|ms)-/)||["",""])[1];return{dom:"WebKit|Moz|MS".match(RegExp("("+a+")","i"))[1],lowercase:a,css:"-"+a+"-",js:a[0].toUpperCase()+a.substr(1)}}();return{show:function(f){var c=document.createElement("div"),g=c.appendChild(document.createElement("div")),k=g.appendChild(document.createElement("div")),h=g.appendChild(document.createElement("div"));
c.style.cssText="position:fixed;left:0;right:0;top:0;bottom:0;text-align:center;line-height:"+(document.body.clientHeight||document.documentElement.clientHeight)+"px";g.style.cssText='padding-top:10px; line-height:30px;display:inline-block;padding:8px; min-width: 80px; background-color:rgba(0,0,0,0.6);border-radius:4px;"';g.align="center";k.style.cssText="width: 24px; height: 24px; display: block; border-radius: 50%; border-left: 2px solid #F36523; border-top: 2px solid #F36523; border-right: 2px solid white; border-bottom: 2px solid white; margin: 16px;";
h.style.cssText='text-align:center;color:#fff;font:normal 12px "microsoft yahei";';h.innerHTML=f;a=document.body.appendChild(c);g="from {"+e.css+"transform:rotate( 0deg ) }to {"+e.css+"transform:rotate( 360deg ) }";f=document.createElement("style");document.head.appendChild(f);f=f.sheet;c="spin_"+(new Date).getTime();g="@"+e.css+"keyframes "+c+"{ "+g+"}";if(d.length){var h=d.pop().name,j=b[h];delete b[h];f.deleteRule(j);f.insertRule(g,j);b[c]=j}else{h=f.cssRules.length;try{f.insertRule(g,h)}catch(t){}b[c]=
h}k.style.cssText+=e.css+"animation:"+c+" 1200ms linear infinite;"},close:function(){a&&(a.parentNode.removeChild(a),a=null)}}}();
MugedaMraid={mraidReadyStatus:0,mraidState:void 0,getStage:function(){var a=null;for(window.event&&(a=window.event.target||window.event.srcElement);a;){if((a.id||"").indexOf("_stage")>0||a.getAttribute&&a.getAttribute("data-mid")==0)break;a=a.parentNode}return a?a:document.getElementsByClassName("MugedaStage")[0]},setMraidState:function(a){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var d=_mrmcp.display_mode,b=mraid.getPlacementType();this.mraidState=a.toLowerCase();var e=document.getElementById("mugeda_close_button");
switch(this.mraidState){case "default":if(d!="expand"&&b!="interstitial"&&e)e.style.display="none";typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(1);break;case "expanded":(d=="auto"||d=="expand"||d=="interstitial")&&setTimeout(function(){e.style.display="block"},50);break;case "resized":setTimeout(function(){e.style.display="block"},50)}},openLink:function(a,d){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;_mrmcp.destination_url&&_mrmcp.destination_url.indexOf("%DESTURL%")<0&&(a=
_mrmcp.destination_url);if(a){var b="ts="+(new Date).getTime();b+="&_moid="+(_mrmcp.owner_id||"");b+="&_mcid="+(_mrmcp.creative_id||"");b+="&_mw="+(_mrmcp.width||"");b+="&_mh="+(_mrmcp.height||"");b+="&_mtp="+(_mrmcp.type||"");b+="&_mtt="+encodeURIComponent(_mrmcp.title||"");var e=_mrmcp.custom_params;e&&e.indexOf("%CUSTOMPARAM%")<0&&(b+="&"+e);if((e=_mrmcp.redirect_url)&&e.indexOf("%LINK%")<0)var f=a.indexOf("?"),c=f<0?"?":"&",a=e+(e.lastIndexOf("=")==e.length-1?encodeURIComponent(a+c+b):"");c=a.split("#");
e="";c.length>1&&(e=c[1],a=c[0]);var f=a.indexOf("?"),c=f<0?"?":"&",f=f==a.length-1,g=window.location.search;if(g){for(var g=g.split("?")[1],k=g.split("&"),h=k.length,j=0;j<h;j++){var t=k[j].split("=");if(t.length==2){var r=t[1];t[0].toLowerCase()=="mugeda_click_link"&&(a=unescape(r),f=a.indexOf("?"),c=a<0?"?":"&",f=f==a.length-1)}}a+=(f?"":c)+g;f=false;g.length&&(c="&")}a+=(f?"":c)+b+(e?"#"+e:"");this.mraidReadyStatus==1?d=="internal"?mraid.open(a):d=="expand"?this.expand(a,0):window.open(a):d==
"internal"?window.location=a:d=="expand"?this.expand(a):window.open(a);MugedaTracker.fireEvent({category:"link",action:d,label:a,value:0})}},expand:function(a,d,b){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;if(this.mraidReadyStatus!=1){if(a&&a.length){var e=document.URL.match(/client.*preview.*id/),f=b=null;try{b=(e?window:window.parent).document,f=b.getElementById("mugeda_expanded")||b.createElement("div")}catch(c){window.open(a);return}a.match(/^(\/|http:|https:)/i)||(a=(_mrmcp.creative_path||
"")+a);f.id="mugeda_expanded";f.style.display="block";f.style.position="fixed";f.style.width=(b.defaultView.innerWidth||b.documentElement.clientWidth)+"px";f.style.height=(b.defaultView.innerHeight||b.defaultView.innerHeight)+"px";f.style.left="0px";f.style.margin="0";f.style.padding="0";f.style.border="none";f.style.top="0px";f.style.background="#000";f.innerHTML="<iframe id='mugeda_expand_iframe' src='"+a+"' style='border:none;width:100%;height:100%;margin:0px;padding:0px;'></iframe>";b.body.appendChild(f);
MugedaBehavior.processCloseButton("expand",b)}}else{var b=b||{},f=mraid.getMaxSize(),e=parseInt(b.width)||f.width,f=parseInt(b.height)||f.height,a=a||b.url,g=!a||a.length==0;d==1?(a=parseInt(b.left)||0,b=parseInt(b.top)||0,MugedaBehavior.processCloseButton("resize"),mraid.setResizeProperties({width:e,height:f,offsetX:a,offsetY:b,allowOffscreen:false}),mraid.resize()):(mraid.setExpandProperties({width:e,height:f,isModal:true,useCustomClose:_mrmcp.display_mode?true:false}),g?(mraid.expand(),MugedaBehavior.processCloseButton()):
mraid.expand(a))}},sendEmail:function(a){window.open("mailto:"+a.email_addr+"?subject="+a.email_title+"&body="+a.email_body,"_self")},savePicture:function(a){this.mraidReadyStatus==1&&mraid.supports("storePicture")&&mraid.storePicture(a.url)},addCalendarEvent:function(a){this.mraidReadyStatus==1&&mraid.supports("calendar")&&mraid.createCalendarEvent({summary:a.calendar_summary,description:a.calendar_desc,location:a.calendar_location,start:a.calendar_start_time,end:a.calendar_end_time})},createHTML5VideoTag:function(a,
d){if(a){var b="_"+ +new Date,e=0,f=0;a.data&&(b="_"+a.data.guid,a.data.param&&(e=a.data.param.continueAudio||0,f=a.data.param.clickStatus||0));var c=G("mugeda_video"+b);if(c)return c.parentNode;div=document.createElement("div");div.className="mugedaVideoHolder";div.style.margin=0;div.style.padding=0;div.style.backgroundColor="rgba(0,0,0,0.8)";div.style.position="absolute";div.style.top=0;div.style.left=0;div.style.width=0;div.style.height=0;div.style.zIndex=1;div.style.display="none";_mrmcp=typeof _mrmcp==
"undefined"?{}:_mrmcp;var g=(_mrmcp.creative_path||"")+"close_button.png",k=navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i);div.innerHTML='<video id="mugeda_video'+b+'" preload="auto" webkit-playsinline="true" video-id="'+d.id+'"  video-mode="'+d.mode+'" video-name="'+d.name+'"  style="width:100%;height:100%;position:absolute;z-index:2;"></video>'+('<div id="mugeda_video_close'+b+'" align="middle" style="position: absolute;color:white;width:36px;height:36px;right:0px;top: '+
(k?0:0)+"px;cursor:pointer;background-image:url("+g+');z-index:3;"></div>');a.appendChild?a.appendChild(div):a.dom&&a.dom.appendChild(div);c=G("mugeda_video"+b);b=G("mugeda_video_close"+b);b.style.display=d.close_button?"block":"none";d.close_button&&(g=isMobile()?"touchend":"click",b.addEventListener(g,function(a){a.stopPropagation();c.src="";c.rawSrc="";c.load();div.style.display="none"},false));d.video_controls?c.setAttribute("controls","controls"):c.removeAttribute("controls");c.rawPlay=c.play;
c.rawPause=c.pause;c.play=function(){c.paused&&(c.onplayed(),c.rawPlay())};c.pause=function(){c.onpaused();c.rawPause()};c.onplayed=function(){if(e==0&&window.backgroundMusic)backgroundMusic.prevPlayStatus=backgroundMusic.playStatus,backgroundMusic.pause(),backgroundMusic.playStatus=0};c.onpaused=function(){if(e==0&&window.backgroundMusic&&backgroundMusic.prevPlayStatus==1)backgroundMusic.play(),backgroundMusic.playStatus=1,delete backgroundMusic.prevPlayStatus};c.onclick=function(a){a.preventDefault();
a.stopPropagation();f===0?this.paused?this.play():this.pause():this.paused&&this.play()};return div}},loadUrl:function(a){var d=a.id||(new Date).getTime(),b=a.url||"",e=a.left||0,f=a.top||0,c=isNaN(a.width)?window.aniData?window.aniData.width:320:Math.max(0,a.width),g=isNaN(a.height)?window.aniData?window.aniData.height:240:Math.max(0,a.height),k=a.before||null,h=a.style,j=a.scroll,t=a.parent,r=a.onload,i=a.onclose,l=a.position,p=a.close_position;if(!k&&!t){var q=typeof Mugeda!="undefined"&&Mugeda.getCanvas?
Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&q&&(q=getElementOffset(q),e+=q.left,f+=q.top)}var m=G(d);m||(m=document.createElement("div"),t?t.appendChild(m):k?k.parentNode.insertBefore(m,k):document.body.appendChild(m));m.id=d;m.style.margin=0;m.style.padding=0;m.style.backgroundColor="transparent";m.style.position=l?l:"fixed";m.style.top=0;m.style.left=0;m.style.width=0;m.style.height=0;switch(p){case "leftTop":p="left:4px;top:4px;";break;case "leftbottom":p="left:4px;bottom:4px;";
break;case "rightbottom":p="right:4px;bottom:4px;";break;default:p="right: 4px;top: 4px;"}m.innerHTML="<iframe "+(j?"":"scrolling=no ")+'id="'+d+'_iframe" style="border:none; width:100%;height:100%; '+(j?"":"overflow:hidden;")+' " ></iframe>'+('<div id="'+d+'_iframe_close" align="middle" style="position: absolute;color:white;width: 24px;height: 24px; '+p+'cursor:pointer;background: rgba(0,0,0,0.5);border: 3px solid white;border-radius: 15px;font-family:arial;font-size: 16px;line-height:24px;">&#10006;</div>');
m.style.display="none";m.style.top=f+"px";m.style.left=e+"px";m.style.width=c+"px";m.style.height=g+"px";m.style.display="block";m.style.cssText+=h;G(d+"_iframe_close").style.display=a.close_button?"block":"none";setTimeout(function(){if(a.close_button)G(d+"_iframe_close").onclick=function(){m.style.display="none";G(d+"_iframe").src="about:blank";i&&i(m)}},100);setTimeout(function(){var a=G(d+"_iframe");a.src=b;if(r)try{a.onload=function(){r(a);a.onload=null}}catch(c){}},100);return m},playAudio:function(a,
d){var b=false;if(!a||!a.audio_url||!a.audio_url.length)return false;var e=typeof Mugeda!="undefined"&&Mugeda.getAudioCache?Mugeda.getAudioCache(a.audio_url,a.audioId):MugedaBehavior.localCache[a.audio_url];if(e){if(e.loop=parseInt(a.audio_loop)==1?true:false,e.play)if(e.webAudio)b=e.play(a.event=="click"||d?true:false);else if(a.event=="click"){try{e.pause(),e.currentTime=0}catch(f){}setTimeout(function(){e.play()},5)}else(e.playStatus!=1||d)&&setTimeout(function(){e.play();e.playStatus=1;b=true},
10)}else{var e=new Audio,c=document.createElement("source"),g=a.audio_url.lastIndexOf("."),g=a.audio_url.substring(g+1),k=true;switch(g){case "ogg":c.type="audio/ogg";break;case "mp3":c.type="audio/mpeg";break;default:k=false,console.log("Audio extension ("+g+") not supported.")}if(k){c.src=a.audio_url;e.appendChild(c);e.autoplay=false;e.preload="auto";e.load();var h=document.getElementById("mugeda_resource_loading");if(!h)h=document.createElement("img"),h.id="mugeda_resource_loading",h.style.position=
"fixed",h.style.right="2px",h.style.top="2px",h.style.display="block",h.src=(_mrmcp.creative_path||"")+"loading.gif",document.body.appendChild(h);h.style.display="block";b=true;e.addEventListener("canplay",function(){h.style.display="none";e.play()},false);MugedaBehavior.localCache[a.audio_url]=e}}return b},playHTML5Video:function(a){var d=a.left||0,b=a.top||0,e=isNaN(a.width)?"100%":Math.max(0,a.width)+"px",f=isNaN(a.height)?"100%":Math.max(0,a.height)+"px",c=window.Mugeda&&Mugeda.getCanvas?Mugeda.getCanvas():
this.getStage();typeof Mugeda!="undefined"&&c&&!a.video_holder&&!isNaN(a.left)&&(c=getElementOffset(c),d+=c.left,b+=c.top);var g=document.body;if(a.video_holder)if((c=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&c.scene){var g=a.video_holder,g=g.split("/"),k=a.video_object===1;if(g.length===2)c=c.scene.getObjectByName(k?g[1]:g[0]),k?(g=c?c.scene.objectHash[g[0]]:null,a.url=g?g.data.param.videoUrl:a.url):g=c?c.scene.getObjectByName(g[1]):null;else if(k){if((g=c.scene.objectHash[a.video_holder])||
(g=c.scene.dom.querySelector('*[data-guid="'+a.video_holder+'"]')),g&&g.data)a.url=g.data.param.videoUrl}else g=c.scene.getObjectByName(a.video_holder)}else{if(window.mugedaCss&&mugedaCss.magic&&(c=document.getElementById(mugedaCss.magic+"stage")))g=a.video_holder,g=g.split("/").map(function(a){return"."+a}),(g=c.querySelectorAll(g.join(" ")))&&g.length&&(g=g[0])}else g=document.body;c=this.createHTML5VideoTag(g,a);c.style.top=b+"px";c.style.left=d+"px";c.style.width=e;c.style.height=f;c.style.display=
"block";var h=c.querySelector("video");h.src=a.url;h.rawSrc=a.url;h.load();setTimeout(function(){h.play();h.playing=true},10)},playVideo:function(a){a=a||{};if(!a.video_url)return false;if(this.mraidReadyStatus!=1){var d=a.dom||document.querySelector('video[video-id="'+a.video_id+'"]');a.video_mode=="object"&&a.video_id&&d&&d.rawSrc==a.video_url||this.playHTML5Video({url:a.video_url,id:a.video_id||"",name:a.video_name||"",mode:a.video_mode||"",video_object:parseInt(a.video_object,10),video_holder:a.video_holder,
left:parseInt(a.video_left,10),top:parseInt(a.video_top,10),width:parseInt(a.video_width,10),height:parseInt(a.video_height,10),close_button:parseInt(a.video_close,10)==1,video_controls:parseInt(a.video_controls,10)==1,auto:parseInt(a.video_autoplay,10)==1})}else mraid.playVideo(a.video_url)},stopVideo:function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),d=0,b=a.length;d<b;d++){var e=a[d].querySelector("video");if(e)e.src="",e.rawSrc="",e.load();a[d]&&(a[d].style.display="none")}},
controlVideo:function(a,d){var b=document.querySelector("#mugeda_video_"+a);if(b)if(d=="play")b.play();else if(d=="pause")b.pause();else{if(d=="stop")b.pause(),b.currentTime=0}else if((b=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&b.scene)if(b=b.scene.objectHash[a]){var e=b.data.param;d==="play"&&MugedaMraid.playVideo({auto:e.videoAutoPlay,clickStatus:e.clickStatus,event_name:"",hidePlayIcon:e.hidePlayIcon,video_close:0,video_continue_audio:e.continueAudio,video_controls:e.hidePlayControls==
1?0:1,video_holder:b.data.guid,video_left:0,video_mode:"object",video_name:e.name,video_object:1,video_top:0,video_url:e.videoUrl})}},sendShortMessage:function(a){window.open("sms:"+a.phone_number+"?body="+a.sms_body,"_self")},makePhoneCall:function(a){window.open("tel:"+a.phone_number,"_self")}};
MugedaBehavior={localCache:{},shakeHash:{},pause:function(){typeof Mugeda!="undefined"&&Mugeda.pause&&Mugeda.pause()},resume:function(a){typeof Mugeda!="undefined"&&Mugeda.resume&&Mugeda.resume(a)},nextPage:function(){typeof Mugeda!="undefined"&&Mugeda.nextPage&&Mugeda.nextPage()},prevPage:function(){typeof Mugeda!="undefined"&&Mugeda.prevPage&&Mugeda.prevPage()},gotoPage:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoPage&&Mugeda.gotoPage(a)},disablePage:function(){typeof Mugeda!="undefined"&&
Mugeda.disablePage&&Mugeda.disablePage()},enablePage:function(){typeof Mugeda!="undefined"&&Mugeda.enablePage&&Mugeda.enablePage()},next:function(){typeof Mugeda!="undefined"&&Mugeda.next&&Mugeda.next()},previous:function(){typeof Mugeda!="undefined"&&Mugeda.previous&&Mugeda.previous()},gotoAndPlay:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(a)},gotoAndStop:function(a){gotoAndPause(a)},gotoAndPause:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPause&&Mugeda.gotoAndPause(a)},
callback:function(a,d){if(window&&d.name&&d.name.length&&window[d.name])window[d.name](a,d.key,d.value)},map:function(a){var d=a.map_key.replace(/(\n|\r)/g,"+"),b=a.map_address.replace(/(\n|\r)/g,"+"),e=navigator.userAgent.toLowerCase().indexOf("android")>-1,f=parseInt(a.map_type,10),c=function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),b=0,c=a.length;b<c;b++)a[b]&&(a[b].style.display="none");(a=G("mugedaMap-mask"))?g(1):(a=document.createElement("div"),b=window._mrmcp&&_mrmcp.creative_path?
_mrmcp.creative_path+"loading.gif":"/images/loading.gif",a.id="mugedaMap-mask",a.className="mugedaMapControl",a.innerHTML='<p id="mugedaMap-title"><a id="mugedaMap-back">\u8fd4\u56de</a>\u4f4d\u7f6e\u4fe1\u606f</p><div id="mugedaMap-con"></div><div id="mugedaMap-loading"><div class="spinner"></div><style>.mugedaMapControl {position:absolute;left:0;top:0;height:100%;width:100%;z-index:999999;}.mugedaMapMaskVisible {-webkit-transition:transform 1s;transform:translate3d(-100%, 0, 0);-webkit-transform:translate3d(-100%, 0, 0);}.mugedaMapControl #mugedaMap-title {position:fixed;height:44px;line-height:44px;width:100%;text-align:center;z-index:1;background:rgba(255,255,255,.8);margin:0;}.mugedaMapControl #mugedaMap-con {height:100%;width:100%;}.mugedaMapControl #mugedaMap-back {position:absolute;left:5px;display:inline-block;height:100%;width:40px;cursor:pointer;}.mugedaMapControl #mugedaMap-loading {position:absolute;width:100%;height:100%;line-height:100%;left:0;top:44px;display:none;background:#fff;z-index:2;}.mugedaMapControl .spinner {position:absolute;width:20px;height:30px;left:50%;top:50%;margin:-50px 0 0 -10px;background-image:url('+
b+');background-repeat:no-repeat;background-size:contain;}.mugedaMapControl .spinner:after {content: "\u52a0\u8f7d\u4e2d ...";position:absolute;width:80px;left:-25px;top:120%;}</style>',document.body.appendChild(a),(a=G("mugedaMap-back"))&&a.addEventListener("click",function(a){a.stopPropagation();g(0)},false))},g=function(a){var b=G("mugedaMap-mask");b&&b.classList.toggle("mugedaMapMaskVisible",!a)},k=function(a){var b=G("mugedaMap-loading");if(b)b.style.display=a?"block":"none"},h,j,t=function(a,
b,c,d){h||(h=new BMap.Map("mugedaMap-con"));h.centerAndZoom(c||"\u5317\u4eac",11);h.addControl(new BMap.ZoomControl);j||(j=new BMap.LocalSearch(h,{renderOptions:{map:h,autoViewport:true},onSearchComplete:function(a){typeof d==="function"&&d.call(h,a)}}));b&&a?j.searchNearby(b,a):j.search(b)},r=function(a,b,d){if(f===0){var e=["http://api.map.baidu.com/getscript?type=quick&file=api&ak=FOm6cLbES9zjrtvcDYndkwSR&v=1.0","http://api.map.baidu.com/getscript?type=quick&file=feature&ak=FOm6cLbES9zjrtvcDYndkwSR&v=1.0"],
b=decodeURIComponent(b),a=decodeURIComponent(a);c();k(1);for(var g=0,d=0,h=e.length;d<h;d++){var j=document.createElement("script");j.src=e[d];j.onload=function(){++g===h&&t(a,b,"",function(a){a.getNumPois()===0&&alert("\u62b1\u6b49\uff0c\u6ca1\u6709\u641c\u7d22\u5230\u76f8\u5173\u4fe1\u606f");k(0)})};document.head.appendChild(j)}}else if(e="https://maps.google.com/maps?q="+(a+""+(b.length?"+near+"+b:""))+"&z=12",j=parseFloat((""+(/CPU.*OS ([0-9_]{1,5})|(CPU like).*AppleWebKit.*Mobile/i.exec(navigator.userAgent)||
[0,""])[1]).replace("undefined","3_2").replace("_",".").replace("_",""))||false,d==1){if(d=document.getElementById("aMugedaGeoLocation"))d.href=e,e=document.createEvent("HTMLEvents"),e.initEvent("click",true,true),d.dispatchEvent(e)}else j&&j<6?window.location.href=e:window.open(e,"_blank")};if(!e&&b.length==0&&navigator.geolocation){a=document.getElementById("aMugedaGeoLocation");if(!a)a=document.createElement("a"),a.id="aMugedaGeoLocation",a.style.display="none",a.href="",a.target="_blank",document.body.appendChild(a);
navigator.geolocation.getCurrentPosition(function(a){b=a.coords.latitude+","+a.coords.longitude;r(d,b,1)})}else r(d,b)},popupForm:function(a,d){function b(a,b){if(a&&b)return a.querySelector("#"+b)}function e(a){if(window.localStorage&&window.localStorage.getItem)return unescape(localStorage.getItem(a)||"");var b,d,c,e=document.cookie.split(";");for(b=0;b<e.length;b++)if(d=e[b].substr(0,e[b].indexOf("=")),c=e[b].substr(e[b].indexOf("=")+1),d=d.replace(/^\s+|\s+$/g,""),d==a.toLowerCase())return unescape(c);
return""}function f(a,b){if(window.localStorage&&window.localStorage.getItem)try{localStorage.setItem(a,escape(b))}catch(d){console.info("Oops, localStorage full"),localStorage.clear(),localStorage.setItem(a,escape(b))}else{var c=new Date;c.setDate(c.getDate()+3);c=escape(b)+"; expires="+c.toUTCString();document.cookie=a.toLowerCase()+"="+c}}function c(a){var b=document.querySelector(".MugedaStage")?null:G("viewbox")||G("frame");if(b)b.style.display=a?"":"none";return b?true:false}function g(a){if(d){var b=
function(a,b){Array.prototype.forEach.call(a,function(a,c){b(a,c)})};b(a.querySelectorAll(".popupFormInputBox input,.popupFormInputBox textarea"),function(a){a.value=""});b(a.querySelectorAll(".popupFormRadioList input,.popupFormCheckbox input"),function(a){a.checked=false});b(a.querySelectorAll(".popupFormSelectList select"),function(a){a.value=a.querySelector("option").getAttribute("value")})}else if(b=a.querySelector("form"),b.style.bottom=-b.offsetHeight+"px",a.style.background="rgba(0,0,0,0)",
setTimeout(function(){a.parentNode&&a.parentNode.removeChild(a)},500),c(1)&&(document.body.style.overflowY="hidden",isMobile()))document.body.style.height="100%"}var k=a.openTarget=="default"||a.openTarget=="frame"||a.openTarget=="page";if(a&&!(a.openTarget=="callback"&&!a.callback||a.openTarget!="callback"&&a.openTarget!="customizable"&&!k&&!a.url)){var k=document.documentElement.clientWidth,h=document.documentElement.clientHeight,j=[],t=function(b,c){var c=c||{},d=c.detail,e=c.form||(d?d.form:null),
d={item:d,form:e,title:a.title,hideItem:function(a){e&&e.elements[a]&&(e.elements[a].parentNode.style.display="none")},showItem:function(a){e&&e.elements[a]&&(e.elements[a].parentNode.style.display="block")}},c=document.createEvent("Events");c.initEvent(b,true,true);c.detail=d;window.dispatchEvent(c)};window.addEventListener("_mugedaFormChanged",function(a){t("mugedaFormChanged",a)});var r=a.items||[];window.popupFormFields=r;if(!a.html){var i="";d?(i+='<div class="popupFormContent">',a.title&&(i+=
'<div align="center" class="popupFormTitle"><h2>'+a.title+"</h2></div>")):(i+='<div align="center" class="popupFormTitle">',i+='<div class="title-col-2" align="center"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel"></div>',i+='<div class="title-col-6" align="center"><h2>'+(a.title||"&nbsp;")+"</h2></div>",i+='<div class="title-col-2" align="center"><input id="actionButton" type="button" value="'+a.submitName+'" class="popupFormSubmit"></div>',i+="</div>",
i+='<div class="popupFormContent">');var l=navigator.userAgent.toLowerCase(),p=l.indexOf("android")>-1,q=parseFloat(l.slice(l.indexOf("android")+8)),m="",z=0,A={phone:"tel",input:"text"};p&&q<3&&(m="-webkit-transform: scale(2,2);-webkit-transform-origin:center center;");for(var B=d?"":":",l=0;l<r.length;l++){var n=r[l],x=(n.value||"").trim();if(x){for(var x=x.split("\n"),u=[],v=0;v<x.length;v++){var I=x[v].split("("),y=I[0],I=(I[1]||"").replace(/\)$/,"")||y,F=["FORMID",I,l,v].join("_");u[v]={id:F,
text:y,value:I}}x=u}F='id="popupFormField_'+l+'"';switch(n.type){case "radio":i+="<div "+F+' class="popupFormRadioList">';n.description&&(i+='<label class="inputlabel">'+n.description+(n.required?"*":"")+B+"</label>");i+='<div class="mformradio">';for(v=0;v<x.length;v++)u=x[v],y=e(u.id),i+='<label><input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="radio" name="'+n.id+'" value="'+
u.value+'" id="'+u.id+'" '+(y=="true"?"checked=checked":"")+" ><span "+(v==x.length-1?"":" style='border-right:1px solid "+a.background+"'")+">"+u.text+"</span></label>",j[u.id]=u.id;i+="</div></div>";break;case "checkbox":i+="<div "+F+' class="popupFormCheckbox">';n.description&&(i+='<label class="inputlabel">'+n.description+(n.required?"*":"")+B+"</label>");i+='<div class="mformcheck">';i+=n.rangeType==="vertical"?"<table>":"";for(v=0;v<x.length;v++)u=x[v],y=e(u.id),i+=n.rangeType==="vertical"?
'<tr><td><input type="checkbox" value="'+u.value+'" id="'+u.id+'" '+(y=="true"?"checked=true":"")+' ></td><td><label for="'+u.id+'" >'+u.text+"</label></td></tr>":'<input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="checkbox" name="'+n.id+'" value="'+u.value+'" id="'+u.id+'" '+(y=="true"?"checked=true":"")+' ><label for="'+u.id+'" >'+u.text+"</label>",j[u.id]=u.id;p&&q<3&&n.rangeType!=
"vertical"&&(z=6);i+=n.rangeType==="vertical"?"</table>":"";i+="</div></div>";break;case "select":i+="<div "+F+' class="popupFormSelectList">';n.description&&(i+='<label class="inputlabel text">'+n.description+(n.required?"*":"")+B+"</label>");i+='<select class="text" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" name="'+n.id+'" id="'+("_map_"+n.description)+'">';i+='<option value="">'+n.description+
"</option>";y=e(n.description);for(v=0;v<x.length;v++)u=x[v],i+='<option value="'+u.value+'" '+(y==u.value?"selected=selected":"")+">"+u.text+"</option>";i+="</select>";i+="</div>";j[n.description]="_map_"+n.description;break;case "textarea":i+="<div "+F+' class="popupFormInputBox">';i+='<label class="inputlabel inputlabel_area">'+n.description+(n.required?"*":"")+B+'</label><textarea name="'+n.id+'" id="_mcp_'+escape(n.description)+'" rows="4" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" style="resize:none; height:48px;">'+
(n.value.length?n.value:e(n.description))+"</textarea>";i+="</div>";j[n.description]="_mcp_"+escape(n.description);break;default:i+="<div "+F+' class="popupFormInputBox">',i+='<label class="inputlabel text">'+n.description+(n.required?"*":"")+B+'</label><input class="text" name="'+n.id+'" id="_mcp_'+escape(n.description)+'" type="'+(A[n.type]||n.type)+"\" onchange=\"var event = document.createEvent('Events');event.initEvent('_mugedaFormChanged', true, true);event.detail = this;window.dispatchEvent(event);\" value=\""+
(e(n.description)||n.value)+'" '+(d?'placeholder="'+n.description+'"':"")+">",i+="</div>",j[n.description]="_mcp_"+escape(n.description)}}d&&(i+='<div class="popupFormBtn"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel">',i+='<input id="actionButton" type="button" value="'+a.submitName+'" class="popupFormSubmit"></div>');i+="</div>";a.html=i}delete this.popupFormDiv;var o=this.popupFormDiv;if(!o){l=function(b){var b=b||".popupForm",c=1;if(/^rgba\(\d+,\s\d+,\s\d+,\s([0-9.]+)\)$/.exec(a.background))c=
RegExp.$1;c="<style>"+b+" {width:100%;font-size:"+a.fontSize+'px;font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+' * {font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+" form{position:absolute;width:100%;background-color:"+a.background+";}"+b+" *{margin:0;box-sizing:border-box;-webkit-appearance: none; -moz-appearance: none; appearance: value;}"+b+" .inputlabel{width:33%;height:28px;font-size:"+a.fontSize+"px;line-height:28px;display:inline-block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;vertical-align:top;color:#000;}"+
b+" span{color:#333;}"+b+" label{color:#000;}"+b+" #popupFormField_0{padding-top:16px;}"+b+" .popupFormMask {position:absolute;left:0;top:0;width:100%;height:100%;background-color: "+a.background+"}"+b+" .popupFormContent {padding-bottom:16px; background-color:#fff;opacity:"+c+";}"+b+" .popupFormTitle {width:100%;padding:20px 0;overflow:hidden;background-color: "+a.background+"}"+b+" h2 {font-weight:normal;font-size:"+(2+parseInt(a.fontSize))+"px;color:"+a.color+";}"+b+" h3{text-align:left;font-size:"+
a.fontSize+"px; font-weight: normal;color:"+a.color+";}"+b+" .popupFormInputBox{padding:8px 16px;text-align:left;}"+b+" .popupFormInputBox input, .popupFormInputBox textarea, .popupFormSelectList select{width:67%;height:28px;border:1px solid "+a.background+";font-size:"+a.fontSize+"px;padding:0;padding-left:8px;vertical-align:top;border-radius:2px;}"+b+" .popupFormSelectList{padding:8px 16px 0;}"+b+" .popupFormRadioList{padding:8px 16px 0;}"+b+" .popupFormCheckbox{padding:8px 16px 0;}"+b+" .popupFormTitle input{border-width:0;cursor:pointer;font-size:"+
a.fontSize+"px;color:"+a.color+"}"+b+" .popupFormSubmit{border:none;background:none}"+b+" .popupFormCancel{background:none;border:none;}"+b+" .popupFormRadioList input{margin:0 5px 0 8px;}"+b+" .popupFormRadioList label{vertical-align:top;}"+b+" .mformradio {background-color:#EFEFEF;border:1px solid "+a.background+";overflow:hidden;display:inline-block;}"+b+" .mformradio label{float:left; min-width:48px;position:relative;}"+b+" .mformradio label span{text-align:center;padding:6px 8px;display:block;}"+
b+" .mformradio label input{position:absolute;width:100%;height:100%;margin:0;border:0;opacity:0;}"+b+" .mformradio input:checked + span{background-color:"+a.background+";color:#F7F7F7;}"+b+" .mformcheck{margin:0 0 8px;display:inline-block;}"+b+" .mformcheck input{"+m+"width:24px;height:24px;background-color:#EFEFEF;border:1px solid "+a.background+";vertical-align:middle;margin:3px 2px;}"+b+" .mformcheck input:checked{background-color:"+a.background+";}"+b+" .popupFormTitle .title-col-2 {float:left;width:20%;padding:0 ;text-align:center;}"+
b+" .popupFormTitle .title-col-6 {float:left;width:60%;padding:0 ;}"+b+" .popupFormTitle .title-col-2 input {font-size:"+(2+parseInt(a.fontSize))+"px;}"+b+" .mformcheck label{vertical-align:"+z+"px;font-size:"+a.fontSize+"px;padding-top:0;padding-left:4px;padding-right:8px;}";d&&(c+=b+" .popupFormBtn {width:100%;padding:20px 0 0 0;text-align:center;}",c+=b+" .popupFormSubmit {width:90px;height:30px;color:"+a.color+";background-color:"+a.background+"}",c+=b+" .popupFormCancel {width:90px;height:30px;margin-right:15px;color:"+
a.color+";display:none;background-color:"+a.background+"}");c+="</style>";return c};if(!o){var J=a.openTarget=="backend"?"popupFormIframe":"_"+a.openTarget,o=document.createElement("div");o.style.display="none";o.className=d?"popupForm2":"popupForm";var C="";if(d)var D=function(b){for(var c={l:48,r:200},d=0,e=0,g=b.length;e<g;e++){for(var h=b[e],f=h.description.length,j=0,i=0;i<f;i++)j+=h.description[i].match(/[\u3400-\u9FBF]/)?2:1;d=Math.max(d,j)}d=d>8?8:d;b=a.fontSize*(d-4);d>4&&d<=8&&(c.l+=b,c.r-=
b);return c}(r),C=l(".popupForm2");else C=l();o.innerHTML='<form method="'+a.method+'" target="'+J+'" autocomplete="on"></form><iframe name="popupFormIframe" id="popupFormIframe" style="display:none"></iframe>'+C;!d&&!a.isCss?document.body.appendChild(o):(a.hwObj=D,a.iframeDiv=o,a.parentDom&&a.parentDom.appendChild(a.iframeDiv));this.popupFormDiv=o;o.form=o.childNodes[0];o.form.onclick=function(){};self=this;d||o.addEventListener(isMobile()?"touchend":"mouseup",function(a){if(!window.cardFrame){if(a.target==
o)g(o),self.popupFormDiv=null,a.stopPropagation();var b=a.target.nodeName.toLowerCase(),c=(a.target.type||"").toLowerCase();["input","textarea","select"].indexOf(b)>=0&&c!="checkbox"&&c!="submit"&&(a.target.focus(),p&&setTimeout(function(){a.target.scrollIntoView();a.target.scrollIntoViewIfNeeded&&a.target.scrollIntoViewIfNeeded()},500),a.stopPropagation());c=="button"&&a.stopPropagation()}});C=function(){function c(){var e=[],h=r;if(!d)h=window.popupFormFields;for(var f=0;f<h.length;f++){var j=h[f],
i=b(o,"popupFormField_"+f),k="",m=i.querySelectorAll("select");m.length==0&&(m=i.querySelectorAll("textarea"),m.length==0&&(m=i.querySelectorAll("input")));if(m.length==1)k=m[0].value||"";else if(m.length>1){for(var k=[],l=0;l<m.length;l++)if(i=m[l],i.checked&&(k.push(i.value),i.type=="radio"))break;k=k.join(",")}if(j.required&&!k){alert((j.description||"item")+" required");m[0].focus();return}if(k)switch(j.type){case "phone":if(!/^\d+$/.test(k)){alert((j.description||"Phone number")+" required");
m[0].focus();return}break;case "email":if(!/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/.test(k)){alert((j.description||"Email")+" required");m[0].focus();return}}a.openTarget==="default"?e.push(encodeURIComponent(j.description+"("+j.id+")")+"="+encodeURIComponent(k||"")):e.push(encodeURIComponent(j.id)+"="+encodeURIComponent(k||""))}if("popupFormIframe"==J)G("actionButton").value=a.pendingName;e=e.join("&");h=a.url+"?"+e;a.loadFinished=function(){g(o);self.popupFormDiv=null};if(a.openTarget=="customizable")h=
{callback:function(){a.msg&&alert(a.msg)},cancel:false},window.MugedaCard&&MugedaCard.finalizeCustomParameters&&MugedaCard.finalizeCustomParameters(e,h),h.cancel!==true&&h.callback(),a.loadFinished();else if(a.openTarget=="default"||a.openTarget=="page"||a.openTarget=="frame"||a.openTarget=="callback"){f="";h=0;if(window._mrmcp)f=window._mrmcp.creative_id||"";else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)f=Mugeda.data.crid;if(f==""&&/\/edit\/(\w+)\&?/.test(top.location.href))f=RegExp.$1,h=f.length<
16?1:2;else if(f==""&&/id=(\w+)\&?/.test(window.location.search))h=3,f=RegExp.$1;j=function(a,b,c){var c=c||"post",d=document.createElement("form"),e=document.createElement("iframe");d.setAttribute("method",c);d.setAttribute("action",a);a="__iframe"+Math.random()*1E4;e.setAttribute("id",a);e.setAttribute("name",a);d.setAttribute("target",a);e.style.width=0;e.style.height=0;e.style.display="none";e.addEventListener("load",function(){});a=0;for(c=b.length;a<c;a++){var h=b[a].split("="),f=h[0],h=h[1],
g=document.createElement("input");g.setAttribute("type","hidden");g.setAttribute("name",f);g.setAttribute("value",h);d.appendChild(g)}document.body.appendChild(d);document.body.appendChild(e);d.submit()};if(f&&/^[a-zA-Z0-9\-\_\.]+\.(mugeda|mgd5|h5mc)\.com$/.test(window.location.hostname))window._mrmcp=window._mrmcp||{},j(_mrmcp.saveFormUrl||"http://weika.mugeda.com/server/cards.php/saveform",(e+"&crid="+f+"&mode="+h).split("&")),a.msg&&alert(a.msg);a.openTarget=="callback"?a.callback&&window[a.callback]?
(h={callback:function(){a.msg&&alert(a.msg)},cancel:false},window[a.callback](e,h),MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",value:a.id?parseInt(a.id,36):0}),h.cancel!==true&&h.callback()):console.log("No callback function found. Skipping..."):a.openTarget=="frame"?a.callback&&a.callback():a.openTarget=="page"&&a.callback&&a.callback();a.loadFinished()}else try{window.open(h,J),G("popupFormIframe").onload=function(){a.loadFinished();MugedaTracker.fireEvent({category:"interaction",
action:"form",label:"",value:a.id?parseInt(a.id,36):0});a.msg&&alert(a.msg)}}catch(n){a.loadFinished(),alert("Form submission failed. Please try again. ")}}o.querySelector("#popupFormIframe").onload=null;for(n in j){var e=document.getElementById(j[n]);e&&(e.type=="checkbox"||e.type=="radio"?f(n,e.checked):f(n,e.value))}q<3?c():setTimeout(c,200);return false}}o.style.display="";o.form.innerHTML=a.html;if(a.id)o.form.id=a.id;var K=isMobile()?"touchstart":"click";o.form.querySelector("input[id=actionButton]").addEventListener(K,
C,false);o.style.display="";o.style.visibility="hidden";setTimeout(function(){t("mugedaFormInitialized",{form:o.form});o.style.visibility="visible"},200);setTimeout(function(){b(o,"popupFormCancel").addEventListener(K,function(){g(o);self.popupFormDiv=null},false)},500);D=o.querySelectorAll(".popupFormInput");for(l=0;l<D.length;l++)C=D[l],C.onfocus=onInputFocus,C.onblur=onInputBlur;var w;a.target?w=a.target.getBoundingClientRect():(D=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&a.isCss?
(k=D.adaption,w={left:Math.max(0,(window.Mugine?1:-1)*k.marginLeft),top:window.Mugine?0:Math.max(0,(window.Mugine?1:-1)*k.marginTop),width:Math.min(k.width,D.width),height:Math.min(k.height,D.height)}):w={left:0,top:0,width:k,height:h};document.body.style.overflowY="auto";if(c()){if(o.style.marginLeft=Math.max(2,w.left+document.documentElement.scrollLeft+(w.width-o.offsetWidth)/2)+"px",o.style.marginTop=Math.max(2,w.top+document.documentElement.scrollTop+(w.height-o.offsetHeight)/2)+"px",o.style.marginBottom=
"32px",o.offsetHeight+32>document.documentElement.scrollHeight&&(o.style.marginTop=parseInt(window.getComputedStyle?getComputedStyle(o).marginTop:o.currentStyle.marginTop)+32+"px",isMobile()))document.body.style.height=o.offsetHeight+64+"px"}else if(o.style.position="relative",o.style.left=w.left+"px",o.style.top=w.top+"px",Math.max(2,w.top+(w.height-o.offsetHeight)/2),Math.max(2,w.left+(w.width-o.offsetWidth)/2),!d){var H=o.querySelector("form");H.style.bottom="-9999px";o.style.overflow="hidden";
setTimeout(function(){o.style.background="rgba(0,0,0,0)";o.style.width=w.width+"px";o.style.height="100%";H.style.webkitTransition="none";H.style.bottom=-H.offsetHeight+"px";setTimeout(function(){H.style.webkitTransition="all 500ms";H.style.bottom="0px";H.style.overflowY="auto";!d&&(o.style.background="rgba(0,0,0,0.3)")},1)},1)}}}},getPopupFormHeight:function(a){for(var d=a.items,b=0,e=0,f=d.length;e<f;e++){var c=d[e];switch(c.type){case "input":case "phone":case "email":b+=44;break;case "textarea":b+=
64;break;case "radio":b+=48;break;case "checkbox":c=c.value.split("\n").length;b+=32*c+8;break;case "select":b+=36;break;default:b+=44}}a.title&&(b+=60);b+=8;b+=50;b+=16;return b},processAction:function(a,d,b,e){var f=true;if(a.type=="pause")this.pause(a.param);else if(a.type=="play")this.resume(1);else if(a.type=="next")this.next();else if(a.type=="previous")this.previous();else if(a.type=="nextPage")this.nextPage();else if(a.type=="prevPage")this.prevPage();else if(a.type=="disablePage")this.disablePage();
else if(a.type=="enablePage")this.enablePage();else if(a.type=="gotoPage"){var c=a.param&&a.param.page_number?a.param.page_number:a.param,g=typeof c=="string"?c.split(";"):[];g.length>1&&(c=g[Math.floor(Math.random()*g.length)]);c=parseInt(c);this.gotoPage(c)}else if(a.type=="callback")this.callback(a.object,a.param);else if(a.type=="map")this.map(a.param);else if(a.type=="gotoAndPlay")c=a.param&&a.param.frame_number?a.param.frame_number:a.param,g=typeof c=="string"?c.split(";"):[],g.length>1&&(c=
g[Math.floor(Math.random()*g.length)]),c=parseInt(c),isNaN(c)&&(c=a.param&&a.param.frame_name?a.param.frame_name:"",c=Mugeda.mapFrameNameId[c],c=parseInt(c)+1),this.gotoAndPlay(c);else if(a.type=="gotoAndPause"||a.type=="gotoAndStop")c=a.param&&a.param.frame_number?a.param.frame_number:a.param,g=typeof c=="string"?c.split(";"):[],g.length>1&&(c=g[Math.floor(Math.random()*g.length)]),c=parseInt(c),isNaN(c)&&(c=a.param&&a.param.frame_name?a.param.frame_name:"",c=Mugeda.mapFrameNameId[c],c=parseInt(c)+
1),this.gotoAndPause(c);else if(a.type=="call")MugedaMraid.makePhoneCall(a.param);else if(a.type=="sms")MugedaMraid.sendShortMessage(a.param);else if(a.type=="email")MugedaMraid.sendEmail(a.param);else if(a.type=="video")MugedaMraid.playVideo(a.param);else if(a.type=="stopVideo")MugedaMraid.stopVideo(a.param);else if(a.type=="audio")a.param.event=d,f=a.restart,window.Mugeda&&Mugeda.getMugedaObject&&(c=Mugeda.getMugedaObject(),c=Math.floor(c.scene.currentId),a.unit&&a.unit.frameStart==c&&(f=true)),
f=MugedaMraid.playAudio(a.param,f);else if(a.type=="picture")MugedaMraid.savePicture(a.param);else if(a.type=="calendar")MugedaMraid.addCalendarEvent(a.param);else if(a.type=="expand")MugedaMraid.expand(a.param.url,0,a.param);else if(a.type=="resize")MugedaMraid.expand("",1,a.param);else if(a.type=="stopAudio")Mugeda.stopAudio&&Mugeda.stopAudio(a.param);else if(a.type=="stopAllAudio")Mugeda.stopAudioAll&&Mugeda.stopAudioAll();else if(a.type=="submitForm"){var k=a.param,c=a.mugeda,g=k.submit_object,
h=k.submit_target||0;window._mrmcp=window._mrmcp||{};var k=h==0?_mrmcp.saveFormUrl||"http://weika.mugeda.com/server/cards.php/saveform":k.submit_url,j="",h=0;if(window._mrmcp&&window._mrmcp.creative_id)j=window._mrmcp.creative_id;else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)j=Mugeda.data.crid,h=3;if(j==""&&/\/edit\/(\w+)\&?/.test(top.location.href))j=RegExp.$1,h=j.length<16?1:2;else if(j==""&&/id=(\w+)\&?/.test(window.location.search))h=3,j=RegExp.$1;if(j&&g){for(var g=g.split(","),h="crid="+j+"&mode="+
h,j={},t=0,r=0;r<g.length;r++){var i=g[r],l=c.scene.getObjectByName(i);if(l)if(l.data.type===2041){var p=l.data.param.name;if(p){var q=l.data.param.required,i=l.dom.querySelector("input:checked");if(q===1&&!i){alert("\u8bf7\u9009\u62e9\u3010"+p+"\u3011\uff0c\u8be5\u9879\u4e0d\u80fd\u4e3a\u7a7a");return}else j[p]=i?i.value:"",t++}}else if(l.data.type===2038){if(p=l.data.param.name)if(q=l.data.param.required,i=document.querySelectorAll("input[name="+p+"]:checked"),q===1&&!i.length){alert("\u8bf7\u9009\u62e9\u3010"+
p+"\u3011\uff0c\u8be5\u9879\u4e0d\u80fd\u4e3a\u7a7a");return}else{for(var q=[],m=0,l=i.length;m<l;m++)q.push(i[m].value);j[p]=q.length?q.join(","):"";t++}}else if(l.data.type===2039)if(q=l.data.param.required,m=unescape(l.data.param.textContent),l=l.dom.querySelector("option:checked"),q===1&&l&&l.innerText===m){alert("\u8bf7\u9009\u62e9\u3010"+m+"\u3011\uff0c\u8be5\u9879\u4e0d\u80fd\u4e3a\u7a7a");return}else h+=l?"&"+i+"="+(l.value!==m?l.value:""):"&"+i+"=",t++;else if((q=l?l.text||"":"")&&i)h+="&"+
i+"="+q,t++}if(t==0)return;k+="?"+h;if(Object.keys(j).length>0)for(p in j)k+="&"+p+"="+j[p];MugedaTools.message.show("\u6b63\u5728\u63d0\u4ea4");ajaxHelper({url:k,type:"jsonp",jsonp_callback:"form_callback",success:function(a){MugedaTools.message.close();e&&e(a)},error:function(){MugedaTools.message.close();e&&e({status:-1})}})}}c="actoin_type="+a.type+"&refid="+(new Date).getTime();for(item in a.param)c+="&"+item+"="+a.param[item];d=="click"&&window.event&&window.event.stopPropagation&&window.event.stopPropagation();
f&&b&&a.param.event_name&&MugedaTracker.fireEvent({category:"interaction",action:a.param.event_name,label:c,value:0})},processCloseButton:function(a,d){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=d,e=null;if(!b)try{window!=window.parent?(b=window.parent.document,e=window.frameElement):b=document}catch(f){b=document}if(b){var c=null;try{c=window.parent.document,c.getElementById("mugeda_expanded")||c.createElement("div")}catch(g){return}var k=a||_mrmcp.display_mode,h=MugedaMraid.mraidReadyStatus==
1?mraid.getPlacementType():"default",j=b.getElementById("mugeda_close_button");if(!j)j=b.createElement("img"),j.id="mugeda_close_button",j.style.cursor="pointer",j.style.zIndex=99999,j.style.display="block",j.style.position="fixed",j.style.right="0",j.style.top="0",j.addEventListener("click",function(){if(MugedaMraid.mraidReadyStatus!=1){b.body.removeChild(j);k=="interstitial"&&e&&e.parentNode.removeChild(e);var a=b.getElementById("mugeda_expanded");a&&b.body.removeChild(a)}}),b.body.appendChild(j);
if(h=="interstitial"||k=="auto"||k=="resize"||k=="expand"||k=="interstitial")j.src=(_mrmcp.creative_path||"")+"close_button.png",j.onerror=function(){j.style.display="none"},j.onload=function(){j.style.display=h=="interstitial"||k!="auto"?"block":"none"}}},setupMobileActionCallback:function(a){MugedaBehavior.actionCallback=a},setupMobileActions:function(a,d,b){function e(a){var b=navigator.userAgent.toLowerCase().indexOf("android")>-1,c=b?15:20,e=b?5:10,t=function(a,g,i,l){if(Math.sqrt(a*a+g*g+i*
i)>=(l?c:e)){a=(new Date).getTime();g=a-(MugedaBehavior.lastHitTime||0);if(!MugedaBehavior.lastHitTime||g>200)MugedaBehavior.shakeNum++,MugedaBehavior.lastHitTime=a;else if(g>1E3)MugedaBehavior.shakeNum=0;if(MugedaBehavior.shakeNum>=(b?1:2)){for(var t in MugedaBehavior.shakeHash){a=MugedaBehavior.shakeHash[t];for(g=0;g<a.length;g++)info=a[g],i=info.object,i=i.displayObject?i.displayObject.realVisible:true,info.callback&&i&&(MugedaBehavior.processAction(info.behavior,info.behavior.event,true),info.callback())}MugedaBehavior.actionCallback&&
MugedaBehavior.actionCallback(f,d.event);MugedaBehavior.shakeNum=0}}},r=0,i=0,l=0;if(a.acceleration===null||a.acceleration.x===void 0||a.acceleration.y===void 0||a.acceleration.z===void 0||a.acceleration.x===null||a.acceleration.y===null||a.acceleration.z===null){if(a.accelerationIncludingGravity)r=a.accelerationIncludingGravity.x,i=a.accelerationIncludingGravity.y,l=a.accelerationIncludingGravity.z,t(r,i,l,1)}else r=a.acceleration.x,i=a.acceleration.y,l=a.acceleration.z,t(r,i,l,0)}var f=a.dataRef||
a.aniData;isMobile();isMobile();isMobile();if(d.event=="shake"&&window.DeviceMotionEvent){if(!window.mugedaShakeHooked)MugedaBehavior.shakeNum=0,window.addEventListener("devicemotion",e,false),window.mugedaShakeHooked=true;var c=a.aniData?a.aniData.guid:null;c&&(MugedaBehavior.shakeHash[c]||(MugedaBehavior.shakeHash[c]=[]),MugedaBehavior.shakeHash[c].push({object:a,callback:b,behavior:d}))}}};
MugedaTracker={fireEvent:function(a){if(!window.location||!window.location.host){var a=(_mrmcp.track_bot||"http://cdn.mugeda.com/media/pages/track/track_20131030.html")+"?"+(_mrmma_var1||"var1=none")+"&"+(_mrmma_var2||"var2=none")+"&category="+a.category+"&action="+a.action+"&label="+encodeURIComponent(a.label)+"&value="+a.value+"&noninteraction="+a.noninteraction,d=document.createElement("iframe");d.id=_mrmcp.creative_id;d.src=a;d.style.display="none";d.style.width="1px";d.style.height="1px";document.body.appendChild(d)}else if(this.fireGAEvent(a.category,
a.action,a.label,a.value,a.noninteraction),this.fireMUEvent(a.category,a.action,a.label,a.value),window.mugedaGetCustomTracker&&(d=window.mugedaGetCustomTracker())){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=_mrmcp.custom_params,e=_mrmma_tags;b&&b.indexOf("%CUSTOMPARAM%")<0&&(e+="&"+b);d(e,a.category,a.action,a.label,a.value)}},fireGAEvent:function(a,d,b,e,f){typeof _gaq!="undefined"&&(_gaq.push(["_trackEvent",a,d,b,e,f]),typeof _ga_mugeda_use_custom!="undefined"&&_gaq.push(["custom._trackEvent",
a,d,b,e,f]))},fireMUEvent:function(a,d,b,e){typeof _mugeda_tracker!="undefined"&&_mugeda_tracker.trackEvent({action:d,category:a,label:b,value:e})}};
function mraidReady(){parseFloat(mraid.getVersion())-0.999>0?(MugedaMraid.mraidReadyStatus=1,_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp,_mrmcp.display_mode&&(mraid.useCustomClose(true),MugedaBehavior.processCloseButton()),mraid.addEventListener("error",function(){}),mraid.addEventListener("stateChange",function(){var a=mraid.getState();MugedaMraid.setMraidState(a)}),mraid.addEventListener("sizeChange",function(){})):console.log("mraidReady is called, but with no correct version (>= 1.0) supported.")}
var mraidReadyTimeout,mraidTimeOut=100,mraidCounter=0;function readyListener(){typeof mraid==="undefined"?(mraidCounter++,mraidCounter<mraidTimeOut&&(mraidReadyTimeout=setTimeout(readyListener,100))):mraid.getState()==="loading"?mraid.addEventListener("ready",mraidReady):mraidReady()}readyListener();
try{var htmlDoc=document.getElementsByTagName("head").item(0),js=document.createElement("script"),s="mraid.js";js.setAttribute("type","text/javascript");js.setAttribute("src",s);htmlDoc.appendChild(js);js.onload=function(){};js.onerror=function(){}}catch(e$$23){alert(e$$23.toString())}
function genSessionId(a){for(var d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=Number(+new Date).toString(36),e=0,f="",c=d.length;e<a;e++)f+=d[Math.floor(Math.random()*c)];return b+f.toLowerCase()}Mugeda=window.Mugeda||{};
Mugeda.playEmbeddedVideo=function(a){a=a.target.parentElement;a.style.display="none";for(var d=0;d<a.parentElement.children.length;d++)a.parentElement.children[d].setAttribute("contenteditable","false");var b=a.previousSibling;b.play();b.onclick=function(){b.controls=b.paused?false:true;b.paused?b.play():b.pause()};if(navigator.userAgent.match(/mqqbrowser.*tbs/i)){for(var e=null;;)if(a=a.parentElement,a.className.indexOf("mugeda_richText_content")>=0){e=a.parentElement;break}else if(a==document.body)break;
var a=e.scrollTop,f=document.createElement("div");f.className="qbrowser_workaround";f.style.position="absolute";f.style.width="1px";f.style.height="1px";f.style.left=0;f.style.top=a+"px";e.appendChild(f);if(e)e.onscroll=function(){f.style.top=e.scrollTop+"px"}}};
Mugeda.Analytics=function(a,d){var b=[],e=0;window._mrmcp=window._mrmcp||{};var f=_mrmcp.impression_pixel?_mrmcp.impression_pixel.indexOf("%TRACKURL%")>=0?"":_mrmcp.impression_pixel:"",a=a||f||"http://cn-stat.mugeda.com/stats/c.gif",d=d||_mrmcp.eventUrl||a;this.setAccount=function(){};this.setCustomVar=function(a,c,d){a=a||0;b[a]&&delete b[a];b[a]={};b[a][c]=d||""};var c=function(a){if(document.cookie.length>0&&(c_start=document.cookie.indexOf(a+"="),c_start!=-1)){c_start=c_start+a.length+1;c_end=
document.cookie.indexOf(";",c_start);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(c_start,c_end))}return""},g=function(){c("clientId");for(var a=[],d=0;d<b.length;d++)for(var e in b[d])a[d]=e+"="+encodeURIComponent(b[d][e]);return a.join("&")},k=function(){var a=location.pathname,b=/(?:\/animation\/edit)|(?:\/page\/edit)|(?:\/default\/preview\.html)|(?:\/client\/preview(?:_css3)?\.html)/;return!location.host||b.test(a)?false:true};this.trackPageview=function(b){if(k()){this.startTime=
(new Date).getTime();var d=a,f=new Image,r=d.indexOf("?")!=-1?"&":"?",i=_mrmcp.title||window._mrmma_title,l=+new Date,p=window.location.host,q=(_mrmcp.width||window._mrmma_width)+"x"+(_mrmcp.height||window._mrmma_height),m=window.location.href.slice(window.location.href.indexOf("/",8)),z=screen.width+"x"+screen.height,b=b||{};b.msv="0.1.0";b.msa="MU-A001";b.msh=p;b.mscs=q;b.msp=m;b.mssr=z;b.mssi=genSessionId(16);b.mscn=i;b.msct=l;b.crid=_mrmcp.creative_id||"";for(var A in b)b.hasOwnProperty(A)&&(this.setCustomVar(e,
A,b[A]),e++);b=c("msuid");if(!b)i=b=genSessionId(32),l=new Date,p=window.location.host.split("."),q=p.length,m="",m=q>=2?"."+p[q-2]+"."+p[q-1]:".mugeda.com",l.setDate(l.getDate()+3650),document.cookie="msuid="+escape(i)+(3650==null?"":";expires="+l.toGMTString())+"; domain="+m+"; path=/";this.setCustomVar(e++,"msuid",b);b=g();f.src=d+r+("mst=1&"+b)}};this.trackEvent=function(a){if(k()){var b=new Image,c=d,e=c.indexOf("?")!=-1?"&":"?",f=g(),a=a||{},l=(new Date).getTime(),p=l-this.startTime,q=encodeURIComponent(a.action||
"submit"),m=encodeURIComponent(a.categroy||"weika"),z=encodeURIComponent(a.label||""),a=parseInt(a.value)||0;b.src=c+e+f+"&mst=2&msts="+l+"&msetd="+p+"&msen="+q+"&msev="+a+"&msec="+m+"&msel="+z}}};try{window._mugeda_tracker=new Mugeda.Analytics,_mugeda_tracker.trackPageview()}catch(e$$24){}
function createFontFaceStyle(a,d,b,e,f,c){var g="cloudfont-"+d;b&&(g+="-"+b);var k=document.getElementById(g),h=Object.prototype.toString.call(e)==="[object Array]"&&typeof f==="function",j=function(a){return(a=RegExp("[?&]"+a+"=([^&#]*)").exec(window.location.href))?a[1]:0};a.toLowerCase()=="simhei"?a='"Microsoft YaHei", "\u5fae\u8f6f\u96c5\u9ed1", SimHei, sans-serif':b&&(a+="-"+b);if(k)return h&&(d=k.textContent.match(/src:url\((.*?)\)/),f(a,d?d[1]:null)),a;else if(c)return null;for(var c=(c=j("fontApiType"))?
c:3,k=e||["eot","eot","woff","ttf","svg"],t=d.indexOf("?")>-1?"&":"?",j=window.bd_version||j("v")||0,r=[],i=e&&e.length,l=e=0,p=function(a,c){var d=document.querySelector(".cloudfont_"+b);d&&document.head.removeChild(d);var e=document.createElement("style"),f,h=function(a){e.id=g;e.className="cloudfont_"+b;a=document.createTextNode(a);e.type="text/css";e.appendChild(a);document.head.appendChild(e)};if(c){var i,j=new window.FileReader;j.readAsDataURL(c);j.onloadend=function(){i=j.result;f="@font-face {font-family:'"+
a+"';\nsrc:url("+i+");}";h(f)}}else f="@font-face {font-family:'"+a+"';\nsrc:"+r[0]+";\nsrc:"+r.slice(1).join(",\n")+";}",h(f)},q=function(b){ajaxHelper({url:b,cache_ok:true,type:"data",success:function(b){++l===i&&typeof f==="function"&&(p(a,b),f(a,b))},error:function(a){a.status==414&&alert(Lang.M_TextTooLong);if(--i===0)throw f(false),"request font failed";}})},m=0,z=k.length;m<z;m++){var A=d+t+"format="+k[m]+"&api_type="+c+"&v="+j,B="url("+A+")";if(m>0){var n=k[m];k[m]==="eot"?n="embedded-opentype":
k[m]==="ttf"&&(n="truetype");B+=" format('"+n+"')"}r.push(B);h&&(e++,q(A))}if(h){if(e===0)throw"request type invalid";}else p(a);return a};
